# Sidebar navigation

- label: 'About'
  link: '/'
- label: Research Groups
  items:
    - label: 'Data visualisation'
      link: '/research-groups/data-visualisation'
    - label: 'Design speculation'
      link: '/research-groups/design-speculation'
    - label: 'Pedagogy'
      link: '/research-groups/pedagogy'
    - label: 'Sonic studies'
      link: '/research-groups/sonic-studies'
 - label: 'People'
   link: '/people'
 - label: 'Get in touch'
   link: '/get-in-touch'
